StoreFront.UI.MVC/Controllers/FiltersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StoreFront.DATA.EF;
using System.Data;
using System.Data.Entity;

namespace StoreFront.UI.MVC.Controllers
{
    public class FiltersController : Controller
    {
        private BurntheMeterEntities db = new BurntheMeterEntities();
        // GET: Filters
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ProductsQS(string searchFilter)
        {
            #region Optional Search Filter

            if (String.IsNullOrEmpty(searchFilter))
            {
                var products = db.Products;
                return View(products.ToList());
            }
            else
            {
                string searchUpCase = searchFilter.ToUpper();

                List<Product> searchResults =
                    (from m in db.Products
                     where m.ProductName.ToUpper().Contains(searchUpCase)
                     select m).ToList();

                return View(searchResults);
            }

            #endregion
        }

        public ActionResult PlatformsFilter(string platform)
        {
            List<Product> platformsFilter =
                (from m in db.Products
                 where m.Platform.PlatformName.Contains(platform)
                 select m).ToList();

            return View(platformsFilter);
        }
    }
}

StoreFront.UI.MVC/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StoreFront.DATA.EF;
using StoreFront.UI.MVC.Utilities;
using StoreFront.UI.MVC.Models;

namespace StoreFront.UI.MVC.Controllers
{
    public class ProductsController : Controller
    {
        private BurntheMeterEntities db = new BurntheMeterEntities();

        // GET: Products
        public ActionResult Index()
        {
            var products = db.Products.Include(p => p.CableType).Include(p => p.Category).Include(p => p.Platform).Include(p => p.StockStatu);
            return View(products.ToList());
        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Products/Create
        public ActionResult Create()
        {
            ViewBag.CableTypeID = new SelectList(db.CableTypes, "CableTypeID", "CableTypeName");
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName");
            ViewBag.PlatformID = new SelectList(db.Platforms, "PlatformID", "PlatformName");
            ViewBag.StockStatusID = new SelectList(db.StockStatus, "StockStatusID", "StockStatus");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductID,ProductName,CategoryID,Price,StockStatusID,PlatformID,CableTypeID,Description,ProductImage")] Product product, HttpPostedFileBase ProductImage)
        {
            if (ModelState.IsValid)
            {

                #region File Upload

                string file = "NoImage.jpg";

                if (ProductImage != null)
                {
                    file = ProductImage.FileName;
                    string ext = file.Substring(file.LastIndexOf('.'));
                    string[] goodExts = { ".jpeg", ".jpg", ".png", ".gif" };
                    if (goodExts.Contains(ext.ToLower()) && ProductImage.ContentLength <= 4194304)
                    {
                        file = Guid.NewGuid() + ext;

                        #region Resize Image

                        string savePath = Server.MapPath("~/Content/imgstore/products/");
                        Image convertedImage = Image.FromStream(ProductImage.InputStream);
                        int maxImageSize = 500;
                        int maxThumbSize = 300;
                        ImageUtility.ResizeImage(savePath, file, convertedImage, maxImageSize, maxThumbSize);

                        #endregion
                    }
                    product.ProductImage = file;
                }

                #endregion

                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CableTypeID = new SelectList(db.CableTypes, "CableTypeID", "CableTypeName", product.CableTypeID);
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName", product.CategoryID);
            ViewBag.PlatformID = new SelectList(db.Platforms, "PlatformID", "PlatformName", product.PlatformID);
            ViewBag.StockStatusID = new SelectList(db.StockStatus, "StockStatusID", "StockStatus", product.StockStatusID);
            return View(product);
        }

        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.CableTypeID = new SelectList(db.CableTypes, "CableTypeID", "CableTypeName", product.CableTypeID);
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName", product.CategoryID);
            ViewBag.PlatformID = new SelectList(db.Platforms, "PlatformID", "PlatformName", product.PlatformID);
            ViewBag.StockStatusID = new SelectList(db.StockStatus, "StockStatusID", "StockStatus", product.StockStatusID);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductID,ProductName,CategoryID,Price,StockStatusID,PlatformID,CableTypeID,Description,ProductImage")] Product product, HttpPostedFileBase ProductImage)
        {
            if (ModelState.IsValid)
            {
                #region File Upload

                string file = product.ProductImage;
                if (ProductImage != null)
                {
                    file = ProductImage.FileName;
                    string ext = file.Substring(file.LastIndexOf('.'));
                    string[] goodExts = { ".jpeg", ".jpg", ".png", ".gif" };
                    if (goodExts.Contains(ext.ToLower()) && ProductImage.ContentLength <= 4194304)
                    {
                        file = Guid.NewGuid() + ext;
                        #region Resize Image

                        string savePath = Server.MapPath("~/Content/imgstore/products/");
                        Image convertedImage = Image.FromStream(ProductImage.InputStream);
                        int maxImageSize = 500;
                        int maxThumbSize = 300;
                        ImageUtility.ResizeImage(savePath, file, convertedImage, maxImageSize, maxThumbSize);

                        #endregion
                        if (product.ProductImage != null && product.ProductImage != "NoImage.png")
                        {
                            string path = Server.MapPath("~/Content/imgstore/products/");
                            ImageUtility.Delete(path, product.ProductImage);
                        }
                        product.ProductImage = file;
                    }
                }

                #endregion

                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CableTypeID = new SelectList(db.CableTypes, "CableTypeID", "CableTypeName", product.CableTypeID);
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName", product.CategoryID);
            ViewBag.PlatformID = new SelectList(db.Platforms, "PlatformID", "PlatformName", product.PlatformID);
            ViewBag.StockStatusID = new SelectList(db.StockStatus, "StockStatusID", "StockStatus", product.StockStatusID);
            return View(product);
        }

        #region OriginalDeleteFunctionality
        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);

            string path = Server.MapPath("~/Content/imgstore/products/");
            ImageUtility.Delete(path, product.ProductImage);

            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        #endregion


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Products()
        {
            var products = db.Products.Include(p => p.CableType).Include(p => p.Category).Include(p => p.Platform).Include(p => p.StockStatu);
            return View(products.ToList());
        }

        #region Custom Add-to-Cart Functionality (Called from Details View)

        public ActionResult AddToCart(int qty, int productID)
        {
            Dictionary<int, CartItemViewModel> shoppingCart = null;

            if (Session["cart"] != null)
            {
                shoppingCart = (Dictionary<int, CartItemViewModel>)Session["cart"];
            }
            else
            {
                shoppingCart = new Dictionary<int, CartItemViewModel>();
            }


            Product product = db.Products.Where(b => b.ProductID == productID).FirstOrDefault();

            if (product == null)
            {
                return RedirectToAction("Products");
            }
            else
            {
                CartItemViewModel item = new CartItemViewModel(qty, product);
                if (shoppingCart.ContainsKey(product.ProductID))
                {
                    shoppingCart[product.ProductID].Qty += qty;
                }
                else
                {
                    shoppingCart.Add(product.ProductID, item);
                }

StoreFront.UI.MVC/Views/Products/Create.cshtml
@model StoreFront.DATA.EF.Product

@{
    ViewBag.Title = "Create";
}
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<h2>Create</h2>


@using (Html.BeginForm("Create", "Products", FormMethod.Post,
    new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProductID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryID, "CategoryID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StockStatusID, "StockStatusID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StockStatusID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StockStatusID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PlatformID, "PlatformID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PlatformID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PlatformID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CableTypeID, "CableTypeID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CableTypeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CableTypeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" style="display:inline" name="ProductImage" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StoreFront.UI.MVC/Views/Products/Delete.cshtml
@model StoreFront.DATA.EF.Product

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductImage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductImage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CableType.CableTypeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CableType.CableTypeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Platform.PlatformName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Platform.PlatformName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StockStatu.StockStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StockStatu.StockStatus)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

StoreFront.UI.MVC/Views/Products/Details.cshtml
@model StoreFront.DATA.EF.Product

<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="~/Content/styles/bootstrap4/bootstrap.min.css">
<link href="~/Content/plugins/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="~/Content/plugins/OwlCarousel2-2.2.1/owl.carousel.css">
<link rel="stylesheet" type="text/css" href="~/Content/plugins/OwlCarousel2-2.2.1/owl.theme.default.css">
<link rel="stylesheet" type="text/css" href="~/Content/plugins/OwlCarousel2-2.2.1/animate.css">
<link rel="stylesheet" href="~/Content/plugins/themify-icons/themify-icons.css">
<link rel="stylesheet" type="text/css" href="~/Content/plugins/jquery-ui-1.12.1.custom/jquery-ui.css">
<link rel="stylesheet" type="text/css" href="~/Content/styles/single_styles.css">
<link rel="stylesheet" type="text/css" href="~/Content/styles/single_responsive.css">

@{
    ViewBag.Title = "Details";
}
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<h2>@Model.ProductName</h2>

<div class="row">
    <div class="col-lg-7">
        <div class="single_product_pics">
            <div class="row">
                <div class="col-lg-3 thumbnails_col order-lg-1 order-2">
                    <div class="single_product_thumbnails">
                        
                    </div>
                </div>
                <div class="col-lg-9 image_col order-lg-2 order-1">
                    <div class="single_product_image">
                        <img class="single_product_image_background" src="~/Content/imgstore/products/t_@Model.ProductImage"/>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-5">
        <div class="product_details">
            <div class="product_details_title">
                <h2>@Model.ProductName</h2>
                <p>@Model.Description</p>
            </div>
            <div class="free_delivery d-flex flex-row align-items-center justify-content-center">
                <span class="ti-truck"></span><span>free delivery</span>
            </div>
            <div class="product_price">$@Model.Price</div>
            <ul class="star_rating">
                <li><i class="fa fa-star" aria-hidden="true"></i></li>
                <li><i class="fa fa-star" aria-hidden="true"></i></li>
                <li><i class="fa fa-star" aria-hidden="true"></i></li>
                <li><i class="fa fa-star" aria-hidden="true"></i></li>
                <li><i class="fa fa-star-o" aria-hidden="true"></i></li>
            </ul>
            
            <p>
                @using (Html.BeginForm("AddToCart", "Products", new { @productID = Model.ProductID }, FormMethod.Post, new { @class = "text-center" }))
                {
                    @Html.HiddenFor(x => x.ProductID)
                    <span class="label" style="color: #000;">Quantity: </span>
                    @Html.TextBox("Qty", 1, new { @class = "form-control", @style = "max-width: 50px; display: inline;" })
                    <input type="submit" value="Add to Cart" class="btn btn-danger" name="qty" />
                }
            </p>
                <div class="product_favorite d-flex flex-column align-items-center justify-content-center"></div>
            </div>
        </div>
    </div>

@*<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            <img src="~/Content/images/@Model.ProductImage" alt="@Model.ProductName" />
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductImage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CableType.CableTypeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CableType.CableTypeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Platform.PlatformName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Platform.PlatformName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StockStatu.StockStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StockStatu.StockStatus)
        </dd>

    </dl>
</div>*@
<script src="~/Scripts/js/jquery-3.2.1.min.js"></script>
<script src="~/Content/styles/bootstrap4/popper.js"></script>
<script src="~/Content/styles/bootstrap4/bootstrap.min.js"></script>
<script src="~/Content/plugins/Isotope/isotope.pkgd.min.js"></script>
<script src="~/Content/plugins/OwlCarousel2-2.2.1/owl.carousel.js"></script>
<script src="~/Content/plugins/easing/easing.js"></script>
<script src="~/Content/plugins/jquery-ui-1.12.1.custom/jquery-ui.js"></script>
<script src="~/Scripts/js/single_custom.js"></script>

StoreFront.UI.MVC/Views/Products/Index.cshtml
@model IEnumerable<StoreFront.DATA.EF.Product>

@{
    ViewBag.Title = "Index";
}

<h2>@ViewBag.Title</h2>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ProductName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductImage)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CableType.CableTypeName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Platform.PlatformName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StockStatu.StockStatus)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ProductName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            <img src="~/Content/imgstore/products/t_@item.ProductImage" alt="Product Image" title="@item.ProductName" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CableType.CableTypeName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Category.CategoryName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Platform.PlatformName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StockStatu.StockStatus)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ProductID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ProductID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ProductID })
        </td>
    </tr>
}

</table>

StoreFront.UI.MVC/Views/Products/Products.cshtml
@model IEnumerable<StoreFront.DATA.EF.Product>

<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="~/Content/styles/bootstrap4/bootstrap.min.css">
<link href="~/Content/plugins/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="~/Content/plugins/OwlCarousel2-2.2.1/owl.carousel.css">
<link rel="stylesheet" type="text/css" href="~/Content/plugins/OwlCarousel2-2.2.1/owl.theme.default.css">
<link rel="stylesheet" type="text/css" href="~/Content/plugins/OwlCarousel2-2.2.1/animate.css">
<link rel="stylesheet" type="text/css" href="~/Content/plugins/jquery-ui-1.12.1.custom/jquery-ui.css">
<link rel="stylesheet" type="text/css" href="~/Content/styles/categories_styles.css">
<link rel="stylesheet" type="text/css" href="~/Content/styles/categories_responsive.css">

<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
@{
    ViewBag.Title = "Products";
}
<h2>@ViewBag.Title</h2>
<div class="">
    <div class="col product_section clearfix">
        <div class="breadcrumbs d-flex flex-row align-items-center">
            <ul>
                <li><a href="@Url.Action("Index", "Home")">Home</a></li>
                <li class="active"><a href="@Url.Action("Products", "Products")"><i class="fa fa-angle-right" aria-hidden="true"></i>Products</a></li>
            </ul>
        </div>
    </div>
</div>
@if (User.IsInRole("Admin"))
{
    <a href="@Url.Action("Index", "Products")" class="btn btn-default">Admin View</a>
}
<br />
<!-- Sidebar -->

<div class="super_container">
    <div class="sidebar">
        <div class="sidebar_section">
            <div class="sidebar_title">
                <h5>Product Category</h5>
            </div>
            <ul class="sidebar_categories">
                <li>@Html.ActionLink("PS4/PS3/PC", "PlatformsFilter", "Filters", new { platform = "PS4/PS3/PC" }, null)</li>
                <li>@Html.ActionLink("Xbone/Xbox Series/PC", "PlatformsFilter", "Filters", new { platform = "Xbone/Xbox Series/PC" }, null)</li>
                <li>@Html.ActionLink("Switch/PC", "PlatformsFilter", "Filters", new { platform = "Switch/PC" }, null)</li>
            </ul>
        </div>
        <br />
        <form method="get" action="/Filters/ProductsQS">
            <div class="form-group">
                <div class="col-sm-2">
                    <label for="searchFilter">Search by Name</label>
                </div>

                <div class="col-xs-offset-1 col-xs-11 col-sm-5">
                    <input type="text" name="searchFilter" />
                </div>
                <br />
                <div class="col-xs-offset-1 col-xs-11 col-sm-2">
                    <input type="submit" value="Go!" class="btn btn-danger" />
                </div>
            </div>
        </form>
    </div>
    <div class="row">
        <div class="col-md-9">
            <div class="product-grid" data-isotope='{ "itemSelector": ".product-item", "layoutMode": "fitRows" }'>
                @foreach (var item in Model)
                {
                    <div class="product-item men" style="padding: 2em">
                        <div class="product product_filter">
                            <div class="product_image">
                                <img src="~/Content/imgstore/products/t_@item.ProductImage" alt="Product Image" title="@item.ProductName" style="padding: 1em" />
                            </div>
                            <div class="favorite favorite_left"></div>
                            <div class="product_info">
                                <h6 class="product_name"><a @Html.ActionLink("Details", "Details", new { id = item.ProductID })>@Html.DisplayFor(modelItem => item.ProductName)</a></h6>
                                <div class="product_price">@Html.DisplayFor(modelItem => item.Price)</div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>



<script src="~/Scripts/js/jquery-3.2.1.min.js"></script>
<script src="~/Content/styles/bootstrap4/popper.js"></script>
<script src="~/Content/styles/bootstrap4/bootstrap.min.js"></script>
<script src="~/Content/plugins/Isotope/isotope.pkgd.min.js"></script>
<script src="~/Content/plugins/OwlCarousel2-2.2.1/owl.carousel.js"></script>
<script src="~/Content/plugins/easing/easing.js"></script>
<script src="~/Content/plugins/jquery-ui-1.12.1.custom/jquery-ui.js"></script>
<script src="~/Scripts/js/categories_custom.js"></script>